const en = {
  home_Title: 'Home Page',
  home_WelcomeMsg: 'Hi, Welcome to Crypto Marketplace',
  home_Hdr_LatestArticle: 'Latest Articles',
  navSide_Home: 'Home',
  navSide_Products: 'Products',
  navSide_Artists: 'Artists',
  navSide_Articles: 'Articles',
  navSide_CreateToken: 'Create Token',
  navSide_BuyerDashBoard: 'Buyer Dashboard',
  navSide_SellerDashBoard: 'Seller Dashboard',
  navSide_QuestionContact1: 'Have Questions?',
  navSide_QuestionContact2: 'or want to become seller',
  navSide_QuestionContact3: 'Contact Us',
  navSide_ShipInfoWelcomeBack: 'Welcome back!',
  navSide_ShipInfoInput1: 'Provide Shipping info',
  navSide_ShipInfoInput2: 'Provide Shipping info',
  notification_barTitle: 'Notifications',
  notification_unread1: 'You have ',
  notification_unread2: ' unread messages',
  notification_barNew: 'New',
  notification_barB4: 'Before that',
  notification_barViewAll: 'View All',
  acctPop_newUser: 'New User',
  acctPop_home: 'Home',
  acctPop_setting: 'Settings',
  donationbar_caption: 'Please enter the USDT amount and..',
  donationbar_noWallet: 'To donate, please CONNECT your wallet first',
  donationbar_button: 'Donate',
  product_Title: 'Dashboard: Products',
  product_Hdr: 'Products',
  product_walletNotFound: 'Please connect your wallet to enable the purchase function',
  productFilter_button: 'Filters',
  productFilter_title: 'Filters',
  productFilter_token: 'Tokens',
  productFilter_clearAll: 'Clear All',
  productSort_title: 'Sort By',
  productSort_byNewest: 'Newest',
  productSort_byName: 'Name',
  productSort_byNameDesc: 'Name Desc',
  articles_title: 'Articles',
  articles_Hdr: 'Articles',
  articlesSort_title: 'Sort By',
  articlesSort_byNewest: 'Newest',
  articlesSort_byAuthor: 'Author',
  articlesSort_byAuthorDesc: 'Author Desc',
  artists_title: 'Parties',
  artists_Hdr: 'Artists/Parties',
  artistsSort_title: 'Sort By',
  artistsSort_byNewest: 'Newest',
  artistsSort_byAuthor: 'Name',
  artistsSort_byAuthorDesc: 'Name Desc',
  ico_Hdr: 'Latest ICO',
  partiesHome_title: 'Artist Home',
  partiesHome_articlesHdr: 'Articles',
  buyerDashboard_title: 'Buyer Dashboard',
  buyerDashboard_Hdr: 'Buyer Dashboard',
  buyerDashboard_latestOrder: 'Latest Orders',
  buyerDashboard_walletNotFound1: 'Wallet not found!',
  buyerDashboard_walletNotFound2: 'Pleast connect the wallet to show your purchase record',
  buyerDashboard_viewAll: 'View all',
  sellerDashboard_title: 'Seller Dashboard',
  sellerDashboard_Hdr: 'Seller Dashboard',
  sellerDashboard_latestICOOrder: 'Pending ICO Orders',
  sellerDashboard_latestOrder: 'Latest Orders Received',
  sellerDashboard_deliveredOrder: 'Delivered Orders',
  sellerDashboard_walletNotFound1: 'Wallet not found!',
  sellerDashboard_walletNotFound2: 'Pleast connect the wallet to show order received',
  sellerDashboard_viewAll: 'View all',
  sellerDashboard_doneItem_checkEthScan: 'Check on Etherscan',
  sellerDashboard_doneItem_tradeIn: 'Traded in',
  sellerDashboard_doneItem_price: 'Price',
  sellerDashboard_doneItem_deliverTo: 'Deilver to',
  sellerDashboard_doneItem_button: 'Item Delivered',
  backDrop_transactionSuccess: 'Transaction Success',
  backDrop_transactionFail: 'Transaction Fail',
  backDrop_caption: 'Press to continue',
  userInfoForm_slogan1: 'You are not necessary to register / login when your wallet is CONNECTED',
  userInfoForm_slogan2: 'AND you can change it anytime',
  userInfoForm_Hdr: 'Please enter your email and delivery information directly',
  userInfoForm_caption: 'We don\'t need any registration',
  userInfoForm_Lbl_username: 'UserName/Recipient',
  userInfoForm_Lbl_email: 'Email address',
  userInfoForm_Lbl_addr1: 'Delivery address line1',
  userInfoForm_Lbl_addr2: 'Delivery address line2',
  userInfoForm_btn: 'OK',
  userInfoForm_wrn_short: 'Too Short!',
  userInfoForm_wrn_long: 'Too Long!',
  userInfoForm_wrn_usernameReq: 'Userame required',
  userInfoForm_wrn_emailReq: 'Email is required',
  userInfoForm_wrn_emailInvalid: 'Email must be a valid email address',
  userInfoForm_wrn_addrReq: 'Address required',
};

export default en;
