const zhHK = {
  home_Title: '主頁',
  home_WelcomeMsg: '歡迎來到 Crypto shop',
  home_Hdr_LatestArticle: '最新消息',
  navSide_Home: '主頁',
  navSide_Products: '商品',
  navSide_Artists: '藝術人/團體',
  navSide_Articles: '文庫',
  navSide_CreateToken: '制作代幣',
  navSide_BuyerDashBoard: '購買記錄',
  navSide_SellerDashBoard: '銷售記錄',
  navSide_QuestionContact1: '有問題?',
  navSide_QuestionContact2: '或有意合作',
  navSide_QuestionContact3: '聯絡我們',
  navSide_ShipInfoWelcomeBack: '歡迎回來!',
  navSide_ShipInfoInput1: '按此',
  navSide_ShipInfoInput2: '提供送貨地點',
  notification_barTitle: '提示信息',
  notification_unread1: '你有 ',
  notification_unread2: ' 個未讀信息',
  notification_barNew: '新信息',
  notification_barB4: '已讀',
  notification_barViewAll: '所有信息',
  acctPop_newUser: '新用戶',
  acctPop_home: '主頁',
  acctPop_setting: '設定',
  donationbar_caption: '請輸入 USDT 數量 ..',
  donationbar_noWallet: '請先連結加密錢包',
  donationbar_button: '捐贈',
  product_Title: '商品',
  product_Hdr: '各項商品',
  product_walletNotFound: '請先連結加密錢包',
  productFilter_button: '篩選',
  productFilter_title: '選項',
  productFilter_token: '加密貨幣名稱',
  productFilter_clearAll: '清除全部',
  productSort_title: '排序:',
  productSort_byNewest: '最新',
  productSort_byName: '名稱',
  productSort_byNameDesc: '名稱(倒序)',
  articles_title: '文庫',
  articles_Hdr: '最新報導',
  articlesSort_title: '排序:',
  articlesSort_byNewest: '最新',
  articlesSort_byAuthor: '作者',
  articlesSort_byAuthorDesc: '作者(倒序)',
  artists_title: '藝術人/團體',
  artists_Hdr: '相關文章',
  artistsSort_title: '排序:',
  artistsSort_byNewest: '最新',
  artistsSort_byAuthor: '名稱',
  artistsSort_byAuthorDesc: '名稱(倒序)',
  ico_Hdr: '最新首次代幣發行活動',
  partiesHome_title: '藝術人/團體主頁',
  buyerDashboard_title: '購買記錄',
  buyerDashboard_Hdr: '購買記錄',
  buyerDashboard_latestOrder: '最近',
  buyerDashboard_walletNotFound1: '未連接加密錢包',
  buyerDashboard_walletNotFound2: '請連接錢包以顯示您的購買記錄',
  buyerDashboard_viewAll: '全部記錄',
  sellerDashboard_title: '銷售記錄',
  sellerDashboard_Hdr: '銷售記錄',
  sellerDashboard_latestICOOrder: '未處理代幣發行',
  sellerDashboard_latestOrder: '最近銷售',
  sellerDashboard_deliveredOrder: '已處理/送貨',
  sellerDashboard_walletNotFound1: '未連接加密錢包',
  sellerDashboard_walletNotFound2: '請連接錢包以顯示您的銷售記錄',
  sellerDashboard_viewAll: '全部記錄',
  backDrop_transactionSuccess: '交易成功',
  backDrop_transactionFail: '交易失敗',
  backDrop_caption: '按此繼續瀏覽',
  userInfoForm_slogan1: '從此你再也不需要花費時間在帳號註冊上',
  userInfoForm_slogan2: '只要連接加密錢包',
  userInfoForm_Hdr: '請直接輸入電郵及送貨地址',
  userInfoForm_caption: '便毋須任何註冊',
  userInfoForm_Lbl_username: '用戶名稱/收件人',
  userInfoForm_Lbl_email: '電郵',
  userInfoForm_Lbl_addr1: '送貨地址 1',
  userInfoForm_Lbl_addr2: '送貨地址 2',
  userInfoForm_btn: '確定',
  userInfoForm_wrn_short: '太短!',
  userInfoForm_wrn_long: '太長!',
  userInfoForm_wrn_usernameReq: '請輸入用戶名稱',
  userInfoForm_wrn_emailReq: '請輸入電郵',
  userInfoForm_wrn_emailInvalid: '電郵地址不正確',
  userInfoForm_wrn_addrReq: '請輸入送貨地址',
};

export default zhHK;